### ISSUE TITLE
Regarding Jira and Confluence Compatible Versions

### ISSUE THREAD

**Issue by vishalbharambe90** [javamelody/jira-confluence-javamelody#21]
Hi Team 
We have upgraded the our prod jira to 8.20.11 so we are looking for the latest java melody plugin but seems 1.91.0 is not compatible to any jira server.
Also second case is we are planning to upgrade our confluence to 7.19 LTS Version here as well we are looking latest javamelody but again the latest 1.91.0  is not compatible to 7.19

As we can see from 1.87.0 there is no jira or confluence version compatible
are you planning to release the new version for jira 8.20.11 and confluence 7.19 server versions?

Thanks

**Comment by phoenixfangor** [comment]
On start-up I'm seeing the following error when I tried to install 1.91.0

```
2022-10-11 18:35:54,194+0200 jira-monitoring-plugin ERROR      [c.a.j.plugins.monitor.MetricsCollectorTask] Error running task
java.lang.NullPointerException
	at com.atlassian.jira.instrumentation.Instrumentation.getInstrument(Instrumentation.java:71)
	at com.atlassian.jira.plugins.monitor.database.ConnectionPoolGraph.setDatasourceValues(ConnectionPoolGraph.java:42)
	at com.atlassian.jira.plugins.monitor.rrd4j.RrdUpdater.addSample(RrdUpdater.java:76)
	at com.atlassian.jira.plugins.monitor.MetricsCollectorTask.doRun(MetricsCollectorTask.java:52)
	at com.atlassian.jira.plugins.monitor.MetricsCollectorTask.run(MetricsCollectorTask.java:41)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)
```

**Comment by evernat** [comment]
> We have upgraded the our prod jira to 8.20.11 so we are looking for the latest java melody plugin but seems 1.91.0 is not compatible to any jira server.
Also second case is we are planning to upgrade our confluence to 7.19 LTS Version here as well we are looking latest javamelody but again the latest 1.91.0 is not compatible to 7.19

Compatibility of versions in the marketplace is not up to date. Just read https://github.com/javamelody/javamelody/wiki/AtlassianPlugin

**Comment by evernat** [comment]
It's funny.

> On start-up I'm seeing the following error when I tried to install 1.91.0
2022-10-11 18:35:54,194+0200 jira-monitoring-plugin ERROR      [c.a.j.plugins.monitor.MetricsCollectorTask] Error running task
java.lang.NullPointerException
	at com.atlassian.jira.instrumentation.Instrumentation.getInstrument(Instrumentation.java:71)
	at com.atlassian.jira.plugins.monitor.database.ConnectionPoolGraph.setDatasourceValues(ConnectionPoolGraph.java:42)
	at com.atlassian.jira.plugins.monitor.rrd4j.RrdUpdater.addSample(RrdUpdater.java:76)
	at com.atlassian.jira.plugins.monitor.MetricsCollectorTask.doRun(MetricsCollectorTask.java:52)
	at com.atlassian.jira.plugins.monitor.MetricsCollectorTask.run(MetricsCollectorTask.java:41)
	at java.base/java.util.TimerThread.mainLoop(Unknown Source)
	at java.base/java.util.TimerThread.run(Unknown Source)

This error is not from the javamelody monitoring plugin. It is from from a monitor plugin of Atlassian to have 1 or 2 graph, which are somewhat similar to some graphs of the javamelody monitoring plugin (including the use of round robin databases).
